[colors]
background = '#fff7f9'
foreground = '#201a1e'

cursor_bg = '#814d78'
cursor_fg = '#fff7f9'
cursor_border = '#814d78'

selection_bg = '#ffd7f3'
selection_fg = '#201a1e'

ansi = ['#171216', '#8c230b', '#09721a', '#757f11', '#fa4bdd', '#6d2060', '#814d78', '#1a1a1a']
brights = ['#2e2e2e', '#a53920', '#138c27', '#8e9921', '#9a568e', '#fc3fff', '#ff5993', '#1a1a1a']
